#!/bin/sh

init_coregl()
{
    cd /usr/lib/

#    file="./libEGL.so"
#    if [ -e $file ]; then
            rm -f ./libEGL.*
            rm -f ./libGLESv2.*

	    ln -s libCOREGL.so libGLESv2.so.2.0
	    ln -s libCOREGL.so libGLESv2.so.2
	    ln -s libCOREGL.so libGLESv2.so

	    ln -s libCOREGL.so libEGL.so.1.4
	    ln -s libCOREGL.so libEGL.so.1
	    ln -s libCOREGL.so libEGL.so
#    fi

    cd -
}

init_coregl

# End of a file
